# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72822617b5d079f00cac1a716929c339a0e9e32cd607200da2b3260c9588519936d500032abb1f7f116f8c22278e567473f1e160cf29d50c28e5f73e4866e71f

test:
  secret_key_base: 3bcfb23c1635e73c7f30b1d17fae04a79e7974be240d6273481be7d06aeb91b0cb9c6c2c87ded390f5108ec226e5c1f031eccf2f597f152a20c38a62098dbed9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
